[meta]
name     = "Ghosts++"
author   = "XertroV"
category = "MLHook"
version  = "0.3.2"
siteid = 444

[script]
#__DEFINES__
dependencies = ["MLHook", "NadeoServices", "VehicleState"]
optional_dependencies = ["ChampionMedals"]
# blocks = ["GhostScrubber"]
timeout = 4000
