[meta]
name     = "Ghost Picker"
author   = "XertroV"
category = "MLHook"
version  = "0.1.3"

[script]
#__DEFINES__
dependencies = ["MLHook", "NadeoServices", "VehicleState"]
optional_dependencies = ["ChampionMedals"]
